- hosts: all
  sudo: True
  roles:
    - common

- hosts: swift_proxy
  sudo: True
  roles:
    - swift_common
    - swift_proxy

- hosts: swift_storage
  sudo: True
  roles:
    - swift_common
    - swift_storage
