  - name: add RDO
    command: yum -y install https://repos.fedorapeople.org/repos/openstack/openstack-kilo/rdo-release-kilo-1.noarch.rpm creates=/etc/yum.repos.d/rdo-release.repo

  - name: install swift
    yum: name={{ item }} state=present
    with_items:
      - curl
      - memcached
      - rsync
      - vim
      - openstack-swift
      - openstack-swift-account
      - openstack-swift-container
      - openstack-swift-object
      - openstack-swift-proxy
