swift_proxy_program_names:
  - swift-proxy-server
  #- swift-object-expirer

swift_account_program_names:
  - swift-account-server
  - swift-account-auditor
  - swift-account-replicator
  - swift-account-reaper
  - swift-account-replicator-server

swift_container_program_names:
  - swift-container-server
  - swift-container-auditor
  - swift-container-replicator
  - swift-container-sync
  - swift-container-updater
  - swift-container-replicator-server

swift_object_program_names:
  - swift-object-server
  - swift-object-auditor
  - swift-object-replicator
  - swift-object-updater
  - swift-object-replicator-server