- name: copy over rsyncd.conf.j2
  template: src=rsyncd.conf.j2 dest=/etc/rsyncd.conf

- name: enable rsync
  lineinfile: dest=/etc/xinetd.d/rsync line="disable = no" create=yes

- name: restart rsync
  service: name=rsyncd state=restarted

- name: ensure *-server directories exist in /etc/swift
  file: path=/etc/swift/{{ item }}-server state=directory owner={{ username }}  group={{ group }} mode=0755
  with_items:
    - account
    - container
    - object

- name: copy over *-server.conf files
  template: src={{ item }}-server.conf.j2 dest=/etc/swift/{{ item }}-server/{{ item }}-server.conf owner=swift group=swift mode=0644
  with_items:
    - account
    - container
    - object
