- name: Restart swift account services
  service:
    name: "{{ item }}"
    state: "restarted"
    pattern: "{{ item }}"
  register: service_restart
  with_items: swift_account_program_names
  failed_when: false

- name: Restart swift container services
  service:
    name: "{{ item }}"
    state: "restarted"
    pattern: "{{ item }}"
  register: service_restart
  with_items: swift_container_program_names
  failed_when: false

- name: Restart swift object services
  service:
    name: "{{ item }}"
    state: "restarted"
    pattern: "{{ item }}"
  register: service_restart
  with_items: swift_object_program_names
  failed_when: false

- name: Restart rsync service
  service:
    name: "rsync"
    state: "stopped"
    pattern: "rsync"
  register: service_restart
  failed_when: "'msg' in service_restart and 'FAIL' in service_restart.msg|upper"
  register: service_restart
  until: add_service|success
  retries: 3
  delay: 2
  notify: Ensure rsync service running

- name: Ensure rsync service running
  service:
    name: "rsync"
    state: "started"
    pattern: "rsync"
